# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GvField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gv_01_open_stock', models.FloatField()),
                ('gv_02_open_stock', models.FloatField()),
                ('gv_03_open_stock', models.FloatField()),
                ('gv_01_close_stock', models.FloatField()),
                ('gv_02_close_stock', models.FloatField()),
                ('gv_03_close_stock', models.FloatField()),
                ('gv_01_open_gauge', models.CharField(max_length=20)),
                ('gv_02_open_gauge', models.CharField(max_length=20)),
                ('gv_03_open_gauge', models.CharField(max_length=20)),
                ('gv_01_close_gauge', models.CharField(max_length=20)),
                ('gv_02_close_gauge', models.CharField(max_length=20)),
                ('gv_03_close_gauge', models.CharField(max_length=20)),
                ('gv_01_stock_change', models.FloatField()),
                ('gv_02_stock_change', models.FloatField()),
                ('gv_03_stock_change', models.FloatField()),
                ('slug', models.SlugField(unique=True)),
                ('pub_date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'GV info',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
    ]
