# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvfield',
            name='incoming_meter_1_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='incoming_meter_1_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='incoming_meter_2_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='incoming_meter_2_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='outgoing_meter_1_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='outgoing_meter_1_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='outgoing_meter_2_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='outgoing_meter_2_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact1_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact1_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact2_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact2_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact3_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact3_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact4_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact4_open',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact5_close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvfield',
            name='tact5_open',
            field=models.FloatField(default=0),
        ),
    ]
