# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneva', '0002_auto_20170130_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GvField',
            new_name='GvData',
        ),
    ]
