# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneva', '0003_auto_20170131_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvdata',
            name='gv_01_close_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_01_open_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_01_stock_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_02_close_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_02_open_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_02_stock_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_03_close_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_03_open_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_03_stock_change',
            field=models.FloatField(default=0),
        ),
    ]
