# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneva', '0004_auto_20170131_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvdata',
            name='gv_01_close_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_01_open_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_02_close_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_02_open_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_03_close_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
        migrations.AlterField(
            model_name='gvdata',
            name='gv_03_open_gauge',
            field=models.CharField(default='0\' 0" /16ths', max_length=20),
        ),
    ]
