# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneva', '0005_auto_20170201_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvdata',
            name='comments',
            field=models.CharField(default='comments', max_length=200),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='gsv_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='incoming_meter_1_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='incoming_meter_2_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='incoming_meter_daily_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='outgoing_meter_1_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='outgoing_meter_2_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='outgoing_meter_daily_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='report_file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='tact1_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='tact2_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='tact3_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='tact4_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='tact5_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gvdata',
            name='transactions_total',
            field=models.FloatField(default=0),
        ),
    ]
